name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  RPC_1: ${{ secrets.RPC_1 }}
  RPC_56: ${{ secrets.RPC_56 }}
  RPC_11155111: ${{ secrets.RPC_11155111 }}
  RPC_10: ${{ secrets.RPC_10 }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: KyberNetwork/foundry-toolchain@master
        with:
          version: v1.4.4

      - name: Build
        run: |
          forge --version
          forge build src --sizes
        id: build

      - name: Run tests
        run: forge test --nmt "testMockActionExecuteSuccessP256|testMockActionExecuteSuccessWebAuthn"
        id: test
        if: always()

      - name: Run tests P256
        run: forge test --mt testMockActionExecuteSuccessP256 --evm-version osaka
        id: test-p256
        if: always()

      - name: Run tests WebAuthn
        run: forge test --mt testMockActionExecuteSuccessWebAuthn --evm-version osaka
        id: test-webauthn
        if: always()
